### ISSUE TITLE
declarative schemas

### ISSUE THREAD

**Issue by ikitommi** [metosin/schema-tools#11]
For web apps, Schemas are used to both validate & document the apis. Would be nice if one could create the schemas more declaratively. There could be a `schema` function in schema-tools that would read declarations (using multimethod dispatch) and create the needed schema structures for those. 

Something like:

``` clojure
(require '[schma.core :as s])
(require '[schema-tools.core :as st])

(s/defschema Model 
  "Model description"
  {:size (st/schema s/Int {:min 10, :max 20, :description "number 10-20"})
   :gender (st/schema (s/enum :male :female) {:description "gender"})})
```

**Comment by mangolas** [comment]
How about describing schema in hiccup style

```clojure
(def Model
  [:model :type/map {:description "Model description"} 
    [:size :type/int {:optional true 
                            :default 0 :min 10 :max 20
                            :description "number 10-20"}]
    [:gender :type/enum {:values [:male :female]
                                      :default :male
                                      :description "gender"}]])
```

**Comment by Deraen** [comment]
Could be alternative, but it would need to be converted to "real" Schema representation by some function. And we still need the Schemas for min/max etc.

**Comment by mangolas** [comment]
Sure, I meant it as a way to describe schema by end user, like me, who just want's to model api ins and outs. Internally it can be the "real" Schema or whatever.

**Comment by ikitommi** [comment]
#32
