### ISSUE TITLE
Use Cljc

### ISSUE THREAD

**Issue by Deraen** [metosin/schema-tools#14]
We don't probably have reason to support Clj <1.7 and using Cljc should make ensuring Cljs compatibility easier.

**Comment by ikitommi** [comment]
agree

**Comment by Deraen** [comment]
This would also break support for <1.7 in Ring-swagger and thus Compojure-api and any other lib which is using Ring-swagger.

**Comment by Deraen** [comment]
Schema plans to support 1.6 at least until 1.8 comes out.
