### ISSUE TITLE
Schema 1.0.0 - support

### ISSUE THREAD

**Issue by ikitommi** [metosin/schema-tools#17]
http://blog.getprismatic.com/schema-1-0-released/

**Comment by dparis** [comment]
Just submitted a PR #18 to resolve this.

**Comment by Deraen** [comment]
Due to fails in CI configuration and cljs test runner, the tests were not run for some time :D Fixed now, once last failing Cljs test is fixed this should be good for release.

**Comment by dparis** [comment]
@Deraen Any idea when v1.0 support might land here and also downstream in compojure-api? I'm available to help this week if it would mean getting some new builds pushed out sooner.

**Comment by Deraen** [comment]
I found the solution for the last failing test so this is probably good for release now.

We are currently very busy with organizing the ClojuTRE so we wont have time for ring-swagger or compojure-api changes this week.

**Comment by Deraen** [comment]
@dparis I have releases Schema-tools 0.6 and pushed snapshot from ring-swagger and compojure-api to clojars. Tests seem to work with minimal or no changes but I didn't do any other testing.

**Comment by dparis** [comment]
@Deraen That's perfect, thank you!

**Comment by dparis** [comment]
Oh, and good luck with ClojuTRE! I'd love to attend if I wasn't all the way over here in Portland, OR USA.
