### ISSUE TITLE
schema-tools.walk/walk doesn't work with s/recursive

### ISSUE THREAD

**Issue by ikitommi** [metosin/schema-tools#29]
`s/recursive` expects it's value to be instance of `clojure.lang.IDeref`, so this line fails:

```clj
(-walk [this inner outer]
  (outer (with-meta (s/recursive (inner (:derefable this))) (meta this))))
```

**Comment by ikitommi** [comment]
https://github.com/plumatic/schema/blob/master/src/cljx/schema/core.cljx#L666

**Comment by Deraen** [comment]
Not sure what we could do here, probably the user has to make sure `inner` returns derefable if it is given one. Maybe we could wrap result in derefable if it isn't one, but I'm not sure if that functionality makes any sense.

**Comment by ikitommi** [comment]
Schema core checks the recursive value with `var?`, so re-wrapping needs to retain the original derefable type. Will resolve this in the client side. Thanks!
