### ISSUE TITLE
Protocol for extracting schema value(s)

### ISSUE THREAD

**Issue by ikitommi** [metosin/schema-tools#8]
currently, schema records hold the value in various fields, one should be able to say:

```clojure
(st/schema-value (s/enum :kikka :kukka))
; [:kikka :kukka]
```

**Comment by Deraen** [comment]
Partially implemented by b9f8f069c486ccdf42f428e0a34f88437a78d128

**Comment by ikitommi** [comment]
:+1:

**Comment by Deraen** [comment]
Still open what to do if trying to access value inside a Schema with multiple sub-schemas, like both, conditional, enum, cond-pre... Perhaps accesing sub-schemas by index would work for most cases?

Enum schema uses sets so indeces don't make sense. Perhaps an exception should be thrown if a value inside enum is accessed?

**Comment by ikitommi** [comment]
What if there were multiple protocols? 

- One for accessing any schema value (enum would return the `:schema`) - good for doc generatipn etc. The original case I had in mind.

-  Another for walking over paths like with  `get-in` & `update-in` -  only implemented for few Records. I think Enum, Defaulted, Named etc. should not be walked over, while Maybe should. Or should it either? Maybe we should not try to invent anything here? If one wants to assoc-in a `s/Str` to a path where there is a `(s/maybe s/Str)`, it should override the whole predicate, not the contents of the Maybe.

thoughts?

**Comment by Deraen** [comment]
> If one wants to assoc-in a s/Str to a path where there is a (s/maybe s/Str), it should override the whole predicate, not the contents of the Maybe.

Good point. Also, if some one want's to get the maybe with `get-in`, that should also be possible.

**Comment by Deraen** [comment]
This was fixed in https://github.com/metosin/schema-tools/commit/dfba9d8d2b5a35c2ba58d1528fe87d63f244aa02

**Comment by neverfox** [comment]
0.9.0 from Clojars:

```
(= s/Str (st/get-in (s/cond-pre {:a s/Str} {:a s/Int}) [0 :a]))
=> false
```

**Comment by Deraen** [comment]
`get-in` and others doesn't use this because we found that confusing (https://github.com/metosin/schema-tools/commit/240f8a5f973d4f6b6036aebcbf110c04909bd65d, https://github.com/metosin/schema-tools/issues/28). To get the value one needs to use [`schema-tools.core/schema-value`](https://github.com/metosin/schema-tools/blob/master/src/schema_tools/core.cljc#L112) directly.

Open to changes later.

**Comment by Deraen** [comment]
One idea I have is that we could use special key to go inside schemas in get-in, update-in and others:

`(st/get-in (s/cond-pre {:a s/Str} {:a s/Int}) [::st/schema-value 0 :a])`

But I don't think is either very useful, is the user does't know in what schemas the value might be wrapped...
